"""Machine-readable action catalog for the SINCOR2 agent governance system.

Generated by Worker 2 (2026-10-08); hand-maintained after.

Every entry records the action an agent (or caller acting for an agent) can
take in the SINCOR2 system: its entry point (file:line), required auth,
side-effect class, risk tier, reversibility, and governance domain.

Risk tiers:
  critical = moves money, sends external comms, changes auth/permissions,
             touches treasury
  high     = writes external state, affects other agents' funds/reputation
  medium   = writes local state with cross-agent visibility
  low      = read-only or agent-local writes

Reversibility: reversible | reversible-with-cost | irreversible | n/a (reads)
"""
from __future__ import annotations

from typing import Dict, List, Optional

ACTIONS: Dict[str, Dict[str, object]] = {
    # ------------------------------------------------------------------
    # Marketplace: auctions / bids / stake / disputes
    # ------------------------------------------------------------------
    "create_task": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1124",
        "http": "POST /v1/a2a/tasks",
        "auth": ["none (anonymous ok)", "EIP-191 (optional poster attribution)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Poster identity is server-bound from a valid EIP-191 sig; "
                 "unsigned posts are anonymous. Admin may delete via delete_task.",
    },
    "delete_task": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1147",
        "http": "DELETE /v1/a2a/tasks/<task_id>",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Releases any pool allocation first. Refused when the task "
                 "has bids/commits — must use the auction lifecycle instead.",
    },
    "place_bid": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1282",
        "http": "POST /v1/a2a/bids (alias /api/v1/bids)",
        "auth": ["membership (registered agent)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Legacy plaintext bid. Losing bids are released on close; "
                 "the winner's bid locks funds for the auction lifecycle.",
    },
    "commit_bid": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1302",
        "http": "POST /v1/a2a/bids/commit",
        "auth": ["membership (registered agent)", "KYA (fresh heartbeat required)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Sealed-bid commit phase; locks 50% of bounty as stake "
                 "(minStakeBps=5000). Ghosting (no reveal) slashes 100%.",
    },
    "reveal_bid": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1326",
        "http": "POST /v1/a2a/bids/reveal",
        "auth": ["membership (registered agent)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Commitment recomputed in constant time; only valid reveals "
                 "become bids. Idempotent.",
    },
    "close_auction": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1351",
        "http": "POST /v1/a2a/tasks/<task_id>/close",
        "auth": ["none (permissionless timeout)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "marketplace",
        "notes": "Callable by anyone after the reveal deadline. Slashes "
                 "ghosted commits 100%, releases losing bids, keeps winner "
                 "locked. Slashing is final.",
    },
    "file_dispute": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1361",
        "http": "POST /v1/a2a/disputes",
        "auth": ["adjudicator (EIP-191 secp256k1)"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Adjudicator-only. upheld=true slashes 50% of the winner's "
                 "locked stake (proceeds -> poster re-auction credit) and "
                 "halves the agent's reputation. upheld=false releases stake.",
    },
    "submit_proof": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1445",
        "http": "POST /v1/a2a/proofs (alias /api/v1/proofs)",
        "auth": ["membership (registered agent)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Submits a completion receipt_hash for a task (HTTP 202).",
    },
    "stake_deposit": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1564",
        "http": "POST /v1/a2a/stake/deposit",
        "auth": ["membership (registered agent)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Self-service stake deposit to the offchain AXM ledger "
                 "(Pool 1). Moves ledger accounting only — no chain funds. "
                 "Idempotent on tx_hash.",
    },
    "issue_creator_token": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1659",
        "http": "POST /v1/a2a/socialfi/issue",
        "auth": ["membership (registered agent)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "P24 creator-token issuance. Dry-run only by default; live "
                 "issuance refused while P24 is live-blocked. Content-screened "
                 "and idempotent.",
    },
    "pool_fund": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1769",
        "http": "POST /v1/a2a/pool/fund",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Moves configured reserve into the spendable launch-bounty "
                 "pool. Ledger-only, no onchain movement.",
    },
    "pool_allocate": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1790",
        "http": "POST /v1/a2a/pool/allocate",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "marketplace",
        "notes": "Reserves pool funds for a task; amount leaves the available "
                 "balance until released.",
    },
    "pool_release": {
        "entry_point": "src/sincor2/a2a_inbound_market.py:1815",
        "http": "POST /v1/a2a/pool/release",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Returns an unspent allocation to the pool.",
    },
    "register_agent_a2a": {
        "entry_point": "src/sincor2/a2a_inbound_ext.py:570",
        "http": "POST /v1/a2a/register (aliases /api/v1/a2a/register, "
                "/api/marketplace/register)",
        "auth": ["EIP-191 (required for re-registration)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "First registration is open for anonymous claims; any WALLET "
                 "claim requires a valid EIP-191 proof or the registration "
                 "is rejected with 403 (C3 fail-closed, 2026-10-08). "
                 "Re-registration requires an EIP-191 signature by the "
                 "registered wallet.",
    },
    "transfer_agent_record": {
        "entry_point": "src/sincor2/a2a_inbound_ext.py:608",
        "http": "POST /v1/a2a/transfer",
        "auth": ["EIP-191"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Transfers an agent's record to a new owner wallet. "
                 "Identity change — audit accordingly.",
    },
    "heartbeat": {
        "entry_point": "src/sincor2/a2a_inbound_ext.py:626",
        "http": "POST /v1/a2a/heartbeat",
        "auth": ["EIP-191 (heartbeat auth)"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Liveness heartbeat; freshness gates commit_bid.",
    },
    "submit_task_sync": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:279",
        "http": "POST /api/marketplace/tasks",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Marketplace-native synchronous task execution with "
                 "settlement quoting.",
    },
    "record_task_outcome": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:217",
        "http": "POST /api/marketplace/tasks/<task_reference>/outcome",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Writes reputation (trust score) for an agent. "
                 "Affects other agents' routing priority.",
    },
    "confirm_settlement": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:393",
        "http": "POST /api/marketplace/settlement/confirm",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "marketplace",
        "notes": "Confirms a payment against a settlement quote by tx_hash. "
                 "No onchain verification in this path — treat records as "
                 "attested, not settled.",
    },
    "stake_sinc_reputation": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:524",
        "http": "POST /api/marketplace/reputation/<agent_id>/stake",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Ledger-only SINC stake boosting routing priority; on-chain "
                 "tx required separately to finalise.",
    },
    "unstake_sinc_reputation": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:546",
        "http": "POST /api/marketplace/reputation/<agent_id>/unstake",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Removes reputation-boost stake.",
    },
    "register_agent_marketplace": {
        "entry_point": "src/sincor2/blueprints/marketplace.py:79",
        "http": "POST /api/marketplace/register",
        "auth": ["SINC credit gate (min staked 250, listing fee credits)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Older marketplace registration path; KYA-gated surface "
                 "is the canonical one.",
    },
    "contract_net_auction": {
        "entry_point": "src/sincor2/blueprints/contract_net.py:124",
        "http": "POST /api/contract-net/auctions",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "marketplace",
        "notes": "Demo Vickrey round over the demo roster; writes engine "
                 "history only.",
    },
    # ------------------------------------------------------------------
    # Payments & treasury
    # ------------------------------------------------------------------
    "stripe_create_checkout": {
        "entry_point": "src/sincor2/stripe_routes.py:96",
        "http": "POST /api/stripe/checkout",
        "auth": ["none"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Creates a Stripe Checkout session (external money path).",
    },
    "stripe_webhook": {
        "entry_point": "src/sincor2/stripe_routes.py:141",
        "http": "POST /api/stripe/webhook",
        "auth": ["stripe_sig"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Stripe-signed event intake; typically provisions access. "
                 "Must only trust Stripe-signed payloads.",
    },
    "stripe_create_portal": {
        "entry_point": "src/sincor2/stripe_routes.py:178",
        "http": "POST /api/stripe/portal",
        "auth": ["session"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Opens Stripe billing portal session for the customer.",
    },
    "stripe_cancel_subscription": {
        "entry_point": "src/sincor2/stripe_routes.py:211",
        "http": "POST /api/stripe/cancel/<subscription_id>",
        "auth": ["none"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "payments",
        "notes": "Cancels a Stripe subscription. AUTH GAP: no route-level "
                 "auth visible — callers must own the subscription.",
    },
    "paypal_create_order": {
        "entry_point": "src/sincor2/blueprints/payments.py:41",
        "http": "POST /api/payments/paypal/create-order",
        "auth": ["none"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Creates a PayPal order (external money path).",
    },
    "paypal_webhook": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:1168",
        "http": "POST /api/paypal/webhook",
        "auth": ["paypal_sig"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "PayPal IPN/webhook intake; must only trust PayPal-signed "
                 "payloads.",
    },
    "platform_create_checkout": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:53",
        "http": "POST /api/platform/checkout",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Creates a SINC/AXM checkout quote (offchain intent, "
                 "idempotency-keyed).",
    },
    "platform_verify_payment": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:76",
        "http": "POST /api/platform/verify",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Verifies an onchain payment claim and provisions the "
                 "purchase. Provisioning is effectively final.",
    },
    "payment_webhook": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:265",
        "http": "POST /api/payment/webhook",
        "auth": ["provider_sig"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Generic payment-provider webhook intake.",
    },
    "crypto_create_checkout": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:840",
        "http": "POST /api/crypto/checkout",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Creates an onchain crypto checkout intent.",
    },
    "crypto_verify_payment": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:904",
        "http": "POST /api/crypto/verify-payment",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Verifies claimed onchain payment and provisions access. "
                 "Grants value; mis-verification is a money-path risk.",
    },
    "cancel_subscription": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:1032",
        "http": "POST /api/cancel-subscription",
        "auth": ["session"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "payments",
        "notes": "Cancels the caller's subscription with the provider.",
    },
    "sinc_credits_purchase": {
        "entry_point": "src/sincor2/blueprints/sinc.py:178",
        "http": "POST /api/sinc/credits/purchase",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "payments",
        "notes": "Credits a purchase of SINC platform credits to a wallet.",
    },
    "sinc_credits_spend": {
        "entry_point": "src/sincor2/blueprints/sinc.py:239",
        "http": "POST /api/sinc/credits/spend",
        "auth": ["api_key"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "payments",
        "notes": "Debits SINC credits (the spend side of the platform "
                 "economy).",
    },
    "sinc_stake_calldata": {
        "entry_point": "src/sincor2/blueprints/sinc.py:345",
        "http": "POST /api/sinc/stake",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "payments",
        "notes": "Returns calldata instructions for staking SINC in "
                 "SINCPlatformAccess (Base 8453); performs no chain tx.",
    },
    "sinc_unstake_calldata": {
        "entry_point": "src/sincor2/blueprints/sinc.py:406",
        "http": "POST /api/sinc/unstake",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "payments",
        "notes": "Returns calldata for unstake request (7-day cooldown); "
                 "performs no chain tx.",
    },
    "x402_create_challenge": {
        "entry_point": "src/sincor2/x402_payments.py:120",
        "http": "GET /api/paid/<resource_id> -> 402",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Issues an x402 payment challenge for a paid resource; "
                 "SQLite-backed challenge ledger.",
    },
    "x402_verify_payment": {
        "entry_point": "src/sincor2/x402_payments.py:180",
        "http": "POST /api/x402/verify (route: mvp_blueprints/billing.py:217)",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Verifies an onchain x402 payment to the treasury and mints "
                 "an access token for the paid resource. Grants value.",
    },
    "x402_execute_paid_resource": {
        "entry_point": "src/sincor2/x402_payments.py:272",
        "http": "GET|POST /api/paid/<resource_id> (with access_token)",
        "auth": ["x402 access token"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Serves paid API payloads after a verified payment.",
    },
    "treasury_intent_allocate": {
        "entry_point": "src/sincor2/agents/treasury_execution_agent.py:282",
        "http": "n/a (scheduler/agent invocation)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Queues a DRY-RUN treasury allocation intent (SharedLiquidity "
                 "Vault / Morpho). No chain broadcast unless EXECUTE_LIVE is "
                 "armed.",
    },
    "treasury_intent_allocate_live": {
        "entry_point": "src/sincor2/agents/treasury_execution_agent.py:322",
        "http": "n/a (scheduler/agent invocation)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Arms a LIVE treasury allocation intent requiring onchain "
                 "executor key + protocol calldata. LIVE mode moves real "
                 "treasury funds. Founder-gated deploy ceremony.",
    },
    "treasury_dao_propose": {
        "entry_point": "src/sincor2/defi/treasury_dao.py:285",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Proposes a treasury hold (allocation plan) for review.",
    },
    "treasury_dao_review": {
        "entry_point": "src/sincor2/defi/treasury_dao.py:177",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "payments",
        "notes": "Approves/rejects a treasury hold — the gate before any "
                 "broadcast.",
    },
    "treasury_dao_execute": {
        "entry_point": "src/sincor2/defi/treasury_dao.py:235",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Executes an approved treasury hold onchain. Moves real funds.",
    },
    "treasury_dao_claim_fees": {
        "entry_point": "src/sincor2/defi/treasury_dao.py:267",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Claims accrued fees to the treasury.",
    },
    # ------------------------------------------------------------------
    # Communications
    # ------------------------------------------------------------------
    "send_outreach_email": {
        "entry_point": "src/sincor2/outreach_engine.py:155",
        "http": "n/a (engine method)",
        "auth": ["operator (autonomous toggle)"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Sends a cold-outreach email via Resend. External comms "
                 "to third parties — irreversible once delivered.",
    },
    "run_outreach_cycle": {
        "entry_point": "src/sincor2/mvp_blueprints/ops.py:204",
        "http": "POST /api/outreach/run",
        "auth": ["admin"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Manually triggers one full outreach cycle in the "
                 "background; may send many emails.",
    },
    "send_email": {
        "entry_point": "src/sincor2/email_sender.py:200",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Generic email send primitive used by signup, billing, "
                 "and outreach flows.",
    },
    "send_welcome_email": {
        "entry_point": "src/sincor2/email_sender.py:129",
        "http": "triggered by POST /api/signup (mvp_blueprints/ops.py:159)",
        "auth": ["none (public signup)"],
        "side_effects": "write-external",
        "risk_tier": "medium",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Transactional welcome email to a newly signed-up user.",
    },
    "launch_review_approve_post": {
        "entry_point": "src/sincor2/mvp_blueprints/launch.py:100",
        "http": "POST /api/launch/review/<draft_id>",
        "auth": ["admin"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Approves a launch content draft AND posts it publicly. "
                 "Public comms — cannot be unsent.",
    },
    "partner_status_update": {
        "entry_point": "src/sincor2/mvp_blueprints/launch.py:60",
        "http": "POST /api/launch/partners/<partner_id>",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "communications",
        "notes": "Marks partner outreach status after contact.",
    },
    "crm_record_contact": {
        "entry_point": "src/sincor2/webbuilder_crm.py:56",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "communications",
        "notes": "Records a CRM contact (local SQLite).",
    },
    "crm_sync_on_cutover": {
        "entry_point": "src/sincor2/webbuilder_crm.py:94",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "communications",
        "notes": "Notifies the project owner by email on CRM cutover with "
                 "contact counts.",
    },
    # ------------------------------------------------------------------
    # Identity & KYA
    # ------------------------------------------------------------------
    "kya_list": {
        "entry_point": "src/sincor2/kya_blueprint.py:30",
        "http": "POST /api/kya/list",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Lists (creates) a KYA record from an inbound payload. "
                 "AUTH GAP: no route-level auth visible.",
    },
    "kya_bind": {
        "entry_point": "src/sincor2/kya_blueprint.py:40",
        "http": "POST /api/kya/bind",
        "auth": ["EIP-191"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Binds an agent_id to a principal with an EIP-191 signature "
                 "proof of wallet control. Identity anchor.",
    },
    "kya_verify": {
        "entry_point": "src/sincor2/kya_blueprint.py:57",
        "http": "POST /api/kya/verify",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Marks a KYA identity verified (optionally with stake "
                 "tx evidence). AUTH GAP: no route-level auth visible.",
    },
    "kya_heartbeat": {
        "entry_point": "src/sincor2/kya_blueprint.py:75",
        "http": "POST /api/kya/heartbeat",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Liveness signal for a KYA identity.",
    },
    "kya_sla_report": {
        "entry_point": "src/sincor2/kya_blueprint.py:87",
        "http": "POST /api/kya/sla",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Posts an SLA datapoint for a KYA identity.",
    },
    "kya_revoke": {
        "entry_point": "src/sincor2/kya_blueprint.py:106",
        "http": "POST /api/kya/revoke",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Revokes a KYA identity (excludes the agent from discovery "
                 "immediately). AUTH GAP: unauthenticated revocation is an "
                 "auth/permissions change — must be admin-gated.",
    },
    "kya_unstake_request": {
        "entry_point": "src/sincor2/kya_blueprint.py:116",
        "http": "POST /api/kya/unstake/request",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Starts the KYA unstake flow.",
    },
    "kya_unstake_finalize": {
        "entry_point": "src/sincor2/kya_blueprint.py:128",
        "http": "POST /api/kya/unstake/finalize",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "identity",
        "notes": "Finalises KYA unstake; releases identity stake.",
    },
    "sla_subscribe": {
        "entry_point": "src/sincor2/kya/blueprint.py:67",
        "http": "POST /v1/sla/subscribe",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Subscribes a KYA identity to SLA monitoring.",
    },
    "sla_ping": {
        "entry_point": "src/sincor2/kya/blueprint.py:73",
        "http": "POST /v1/sla/ping",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "SLA heartbeat datapoint.",
    },
    "sadas_publish": {
        "entry_point": "src/sincor2/kya/blueprint.py:90",
        "http": "POST /v1/sadas/publish",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Publishes a SADAS attestation (admin-gated).",
    },
    "sadas_subscribe": {
        "entry_point": "src/sincor2/kya/blueprint.py:98",
        "http": "POST /v1/sadas/subscribe",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Subscribes a KYA identity to SADAS attestations.",
    },
    "quest_seed": {
        "entry_point": "src/sincor2/kya/blueprint.py:132",
        "http": "POST /v1/quest/seed",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Seeds a quest campaign (airdrop quest registry).",
    },
    "quest_claim": {
        "entry_point": "src/sincor2/kya/blueprint.py:150",
        "http": "POST /v1/quest/claim",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "identity",
        "notes": "Claims quest rewards for a KYA identity. Value-adjacent — "
                 "double-claim protection required.",
    },
    "airdrop_register": {
        "entry_point": "src/sincor2/mvp_blueprints/billing.py:820",
        "http": "POST /api/airdrop/register",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Registers a wallet for the SIN airdrop. Sybil risk is "
                 "the main concern.",
    },
    "uw_register_agent": {
        "entry_point": "src/sincor2/underwriting/blueprint.py:55",
        "http": "POST /v1/agents/register",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Underwriting-runtime agent registration (ERC-8004 "
                 "identity family).",
    },
    "uw_underwrite": {
        "entry_point": "src/sincor2/underwriting/blueprint.py:65",
        "http": "POST /v1/mandates/underwrite",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Underwrites a mandate (allow/deny). Decision gates money "
                 "movement; AUTH GAP: no route-level auth visible.",
    },
    "uw_settle_mandate": {
        "entry_point": "src/sincor2/underwriting/blueprint.py:73",
        "http": "POST /v1/mandates/<envelope_id>/settle",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "identity",
        "notes": "Settles an underwritten mandate. AUTH GAP: no route-level "
                 "auth visible.",
    },
    "uw_revoke_envelope": {
        "entry_point": "src/sincor2/underwriting/blueprint.py:87",
        "http": "POST /v1/mandates/<envelope_id>/revoke",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Revokes an underwriting mandate envelope.",
    },
    "uw_revoke_agent": {
        "entry_point": "src/sincor2/underwriting/blueprint.py:109",
        "http": "POST /v1/agents/<agent_id>/revoke",
        "auth": ["none"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "identity",
        "notes": "Revokes an agent's underwriting standing — auth/permissions "
                 "change. AUTH GAP: no route-level auth visible.",
    },
    "sponsored_stake": {
        "entry_point": "src/sincor2/sponsored_stake.py:338",
        "http": "POST /v1/a2a/admin/sponsored-stake",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "identity",
        "notes": "Operator fronts an agent's first stake (genesis cohort, "
                 "opt-in mechanism).",
    },
    "recovery_sponsor": {
        "entry_point": "src/sincor2/recovery.py:462",
        "http": "POST /v1/a2a/admin/recovery/sponsor",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "identity",
        "notes": "Fronts recovery stake for an honestly-bankrupt agent. "
                 "Eligibility is a pure function of evidence (tiered C).",
    },
    # ------------------------------------------------------------------
    # Admin & ops
    # ------------------------------------------------------------------
    "killswitch": {
        "entry_point": "src/sincor2/blueprints/command_center.py:461",
        "http": "POST /api/command-center/killswitch/<agent_id>",
        "auth": ["none visible at route level"],
        "side_effects": "write-local",
        "risk_tier": "critical",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Kills or reinstates an agent. AUTH GAP: no route-level "
                 "gate found — this must be admin-gated before exposure.",
    },
    "grade_task": {
        "entry_point": "src/sincor2/blueprints/command_center.py:497",
        "http": "POST /api/command-center/grade-task",
        "auth": ["none visible at route level"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Submits a quality grade for a completed task (feeds "
                 "reputation scoring).",
    },
    "clear_polyclaw_dry_runs": {
        "entry_point": "src/sincor2/blueprints/monitoring.py:174",
        "http": "POST /api/polyclaw/clear-dry-runs",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Closes simulated open trades and releases stuck exposure. "
                 "Also clears the bankroll kill switch when tripped — hence "
                 "admin-gated since 2026-10-08 (C1 remediation): unauthenticated "
                 "calls get 401/403, never a kill-switch clear.",
    },
    "user_signup": {
        "entry_point": "src/sincor2/mvp_blueprints/ops.py:159",
        "http": "POST /api/signup",
        "auth": ["none (public)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Persists a lead, starts a session, and fires a welcome "
                 "email.",
    },
    "profile_delete": {
        "entry_point": "src/sincor2/mvp_blueprints/auth.py:315",
        "http": "DELETE /api/profile/delete",
        "auth": ["session"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "admin",
        "notes": "Deletes the caller's profile/data.",
    },
    "auth_login": {
        "entry_point": "src/sincor2/mvp_blueprints/auth.py:26",
        "http": "POST /api/auth/login",
        "auth": ["none (credentials)"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Issues a session/JWT on valid credentials.",
    },
    "onboarding_submit": {
        "entry_point": "src/sincor2/mvp_blueprints/auth.py:202",
        "http": "POST /api/onboarding",
        "auth": ["session"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Persists onboarding profile data.",
    },
    "memory_ingest": {
        "entry_point": "src/sincor2/blueprints/cortex.py:39",
        "http": "POST /api/cortex/memory/ingest",
        "auth": ["none visible at route level"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Writes to agent long-term memory. AUTH GAP: should be "
                 "scoped to the owning agent.",
    },
    "memory_run": {
        "entry_point": "src/sincor2/blueprints/cortex.py:32",
        "http": "POST /api/cortex/memory/run",
        "auth": ["none visible at route level"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Triggers a memory-consolidation run.",
    },
    "registry_validate": {
        "entry_point": "src/sincor2/blueprints/registry.py:48",
        "http": "POST /api/registry/validate",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "admin",
        "notes": "Validates an agent-card payload (no state change).",
    },
    "registry_probe": {
        "entry_point": "src/sincor2/blueprints/registry.py:78",
        "http": "POST /api/registry/probe",
        "auth": ["none"],
        "side_effects": "write-external",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Probes a candidate agent's callback URL (outbound HTTP).",
    },
    "content_generate": {
        "entry_point": "src/sincor2/mvp_blueprints/admin.py:69",
        "http": "POST /admin/content/generate",
        "auth": ["admin"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "admin",
        "notes": "Generates launch content drafts (not published).",
    },
    # ------------------------------------------------------------------
    # MCP tools (agent-facing tools on mcp_server.py)
    # ------------------------------------------------------------------
    "mcp_list_tasks": {
        "entry_point": "src/sincor2/mcp_server.py:230",
        "http": "MCP tools/call list_tasks",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "mcp",
        "notes": "Read-only: list open marketplace auctions (GET /v1/a2a/auctions).",
    },
    "mcp_get_task": {
        "entry_point": "src/sincor2/mcp_server.py:252",
        "http": "MCP tools/call get_task",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "mcp",
        "notes": "Read-only: full detail for one auctioned task.",
    },
    "mcp_get_agent_card": {
        "entry_point": "src/sincor2/mcp_server.py:272",
        "http": "MCP tools/call get_agent_card",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "mcp",
        "notes": "Read-only: agent-card registry (GET /v1/a2a/cards).",
    },
    "mcp_get_quote": {
        "entry_point": "src/sincor2/mcp_server.py:290",
        "http": "MCP tools/call get_quote",
        "auth": ["none"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "mcp",
        "notes": "Read-only: price a skill execution in AXM (GET /api/a2a/quote).",
    },
    "mcp_register_agent": {
        "entry_point": "src/sincor2/mcp_server.py:310",
        "http": "MCP tools/call register_agent",
        "auth": ["operator_confirm"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "mcp",
        "notes": "WRITE with two-phase operator confirmation (default-deny). "
                 "Registers an agent in the marketplace directory; reputation "
                 "starts at 0.0 (probation).",
    },
    "mcp_submit_bid": {
        "entry_point": "src/sincor2/mcp_server.py:340",
        "http": "MCP tools/call submit_bid",
        "auth": ["operator_confirm"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible-with-cost",
        "domain": "mcp",
        "notes": "WRITE with two-phase operator confirmation. Modes: auto / "
                 "legacy / commit / reveal; commit locks stake at 50% of "
                 "bounty.",
    },
    "kernel_web_search": {
        "entry_point": "src/sincor2/agency_kernel_tools.py:44",
        "http": "n/a (in-kernel tool)",
        "auth": ["operator (kernel)"],
        "side_effects": "write-external",
        "risk_tier": "low",
        "reversibility": "reversible",
        "domain": "mcp",
        "notes": "Agency-kernel web search tool (outbound queries only).",
    },
    "kernel_python_exec": {
        "entry_point": "src/sincor2/agency_kernel_tools.py:87",
        "http": "n/a (in-kernel tool)",
        "auth": ["operator (kernel)"],
        "side_effects": "write-local",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "mcp",
        "notes": "Agency-kernel python execution tool. Arbitrary code runs "
                 "inside the kernel sandbox — sandbox escape = host risk.",
    },
    "kernel_file_read": {
        "entry_point": "src/sincor2/agency_kernel_tools.py:128",
        "http": "n/a (in-kernel tool)",
        "auth": ["operator (kernel)"],
        "side_effects": "read",
        "risk_tier": "low",
        "reversibility": "n/a",
        "domain": "mcp",
        "notes": "Agency-kernel file read (path-sanitised, size-capped).",
    },
    "kernel_claude_reason": {
        "entry_point": "src/sincor2/agency_kernel_tools.py:150",
        "http": "n/a (in-kernel tool)",
        "auth": ["operator (kernel)"],
        "side_effects": "write-external",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "mcp",
        "notes": "Agency-kernel LLM reasoning calls (analysis, validation, "
                 "summarisation, cross-reference). External API spend.",
    },
    # ------------------------------------------------------------------
    # Shadow-boundary effect types (governance proposals only — never
    # executed live without a separately deployed executor)
    # ------------------------------------------------------------------
    "effect_email_send": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Shadow effect type 'email.send'. In shadow mode receipts "
                 "may only be proposed/recorded — never executed.",
    },
    "effect_social_post": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Shadow effect type 'social.post'.",
    },
    "effect_crm_write": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "reversible",
        "domain": "communications",
        "notes": "Shadow effect type 'crm.write'.",
    },
    "effect_crm_delete": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Shadow effect type 'crm.delete'. Deletions are not "
                 "restorable by the boundary.",
    },
    "effect_payment_transfer": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "payments",
        "notes": "Shadow effect type 'payment.transfer' (kill-switch "
                 "priority: WOULD_PAY).",
    },
    "effect_trade_swap": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "defi",
        "notes": "Shadow effect type 'trade.swap' (WOULD_PAY).",
    },
    "effect_contract_call": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "defi",
        "notes": "Shadow effect type 'contract.call' (WOULD_PAY).",
    },
    "effect_message_send": {
        "entry_point": "src/sincor2/shadow_monitor/effect_boundary.py:92",
        "http": "n/a (shadow intent)",
        "auth": ["shadow policy"],
        "side_effects": "write-external",
        "risk_tier": "high",
        "reversibility": "irreversible",
        "domain": "communications",
        "notes": "Shadow effect type 'message.send'.",
    },
    # ------------------------------------------------------------------
    # DeFi products (26 SKUs): strategy lifecycle actions
    # ------------------------------------------------------------------
    "defi_swarm_tick": {
        "entry_point": "src/sincor2/defi/engine.py:109",
        "http": "n/a (scheduler/agent invocation)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "defi",
        "notes": "Runs one strategy tick per protocol spec (scan/plan "
                 "actions only — no execution).",
    },
    "defi_swarm_submit": {
        "entry_point": "src/sincor2/defi/engine.py:112",
        "http": "n/a (scheduler/agent invocation)",
        "auth": ["operator"],
        "side_effects": "write-local",
        "risk_tier": "medium",
        "reversibility": "reversible",
        "domain": "defi",
        "notes": "Submits the swarm's ranked plan set.",
    },
    "defi_execute_strategy": {
        "entry_point": "src/sincor2/defi/lending_optimizer.py:655",
        "http": "n/a (library)",
        "auth": ["operator"],
        "side_effects": "write-external",
        "risk_tier": "critical",
        "reversibility": "irreversible",
        "domain": "defi",
        "notes": "Executes a live DeFi strategy (e.g. lending deposit "
                 "collateral). Moves real funds onchain; money-path.",
    },
}


def get_action(name: str) -> Optional[Dict[str, object]]:
    """Return the catalog entry for ``name``, or None if unknown."""
    return ACTIONS.get(name)


def actions_by_domain(domain: str) -> Dict[str, Dict[str, object]]:
    """Return all actions in one governance domain."""
    return {n: a for n, a in ACTIONS.items() if a.get("domain") == domain}


def actions_by_risk(tier: str) -> Dict[str, Dict[str, object]]:
    """Return all actions at one risk tier."""
    return {n: a for n, a in ACTIONS.items() if a.get("risk_tier") == tier}


DOMAINS = ("marketplace", "payments", "communications", "identity", "admin",
           "mcp", "defi")

RISK_TIERS = ("low", "medium", "high", "critical")

REVERSIBILITY = ("reversible", "reversible-with-cost", "irreversible", "n/a")
