"""
SINAX — Phase 6: Lemma Discovery Engine
==========================================
Identifies repeated failure regions in the proof graph, clusters them, and
generates candidate bridging lemmas.  Every candidate is routed through the
active verifier before being stored or surfaced.

Workflow
--------
1. **Detect bottlenecks** — gather nodes/edges with high failure density
   (via ``CurvatureAnalyzer``).
2. **Cluster failures** — group failed-edge source nodes by embedding
   similarity (greedy single-linkage in embedding space).
3. **Generate candidate lemmas** — propose a bridging lemma for each
   non-trivial cluster (using the cluster centroid and most common goal
   fragments).
4. **Rank and verify** — score candidates by potential impact; route
   each through the verifier; only return verified lemmas.

Public API
----------
    LemmaCandidate      — value object
    LemmaDiscoveryEngine
    get_lemma_engine()  — singleton accessor
"""

from __future__ import annotations

import hashlib
import logging
import math
import threading
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

import numpy as np

from . import config as cfg
from .curvature import CurvatureAnalyzer, get_curvature_analyzer
from .encoder import Embedding, get_encoder
from .graph_store import (
    ProofStateNode,
    ProofGraphStore,
    TacticEdge,
    VerificationResult,
    get_store,
)

logger = logging.getLogger("sincor.sinax.lemma_discovery")

# ---------------------------------------------------------------------------
# Verifier abstraction
# ---------------------------------------------------------------------------


class Verifier:
    """Thin adapter around the active proof verifier (Lean or other backend).

    By default, delegates to the environment-configured backend.  In
    environments where Lean is not available, the call always returns
    ``VerificationResult.PENDING``.  Replace this class or monkey-patch
    ``Verifier.verify`` to integrate with a real Lean subprocess.
    """

    def verify(self, statement: str, proof_sketch: str = "") -> VerificationResult:
        """Attempt to verify ``statement``.

        Parameters
        ----------
        statement:
            The formal lemma statement (e.g. Lean 4 syntax).
        proof_sketch:
            Optional proof sketch / tactic sequence to check.

        Returns
        -------
        ``VerificationResult.VERIFIED`` / ``FAILED`` / ``PENDING``
        """
        backend = cfg.VERIFIER_BACKEND
        if backend == "lean":
            return self._verify_lean(statement, proof_sketch)
        # "none" or unrecognised backend → mark pending
        logger.debug("Verifier backend '%s': returning PENDING", backend)
        return VerificationResult.PENDING

    def _verify_lean(self, statement: str, proof_sketch: str) -> VerificationResult:
        """Call Lean 4 subprocess to verify the statement.

        This is a best-effort implementation that tries to invoke ``lean``
        from the PATH.  Falls back to PENDING when Lean is not installed.
        """
        import subprocess
        import tempfile
        import os

        lean_source = f"-- SINAX auto-generated lemma\n{statement}\n{proof_sketch}\n"
        try:
            with tempfile.NamedTemporaryFile(
                suffix=".lean", mode="w", delete=False
            ) as f:
                f.write(lean_source)
                fname = f.name
            result = subprocess.run(
                ["lean", "--stdin"],
                input=lean_source,
                capture_output=True,
                text=True,
                timeout=cfg.VERIFIER_TIMEOUT_SECONDS,
            )
            os.unlink(fname)
            if result.returncode == 0:
                return VerificationResult.VERIFIED
            logger.debug("Lean verification failed:\n%s", result.stderr[:500])
            return VerificationResult.FAILED
        except FileNotFoundError:
            logger.debug("lean binary not found; returning PENDING")
            return VerificationResult.PENDING
        except subprocess.TimeoutExpired:
            logger.warning("Lean verification timed out for: %s", statement[:80])
            return VerificationResult.FAILED
        except Exception as exc:
            logger.warning("Lean verification error: %s", exc)
            return VerificationResult.PENDING


# ---------------------------------------------------------------------------
# Value objects
# ---------------------------------------------------------------------------


@dataclass
class LemmaCandidate:
    """A candidate bridging lemma generated by the discovery engine.

    Attributes
    ----------
    lemma_id:
        Stable hash-based identifier.
    statement:
        Formal lemma statement (Lean or natural language, depending on
        how the candidate was generated).
    proof_sketch:
        Optional proof strategy or tactic sequence.
    cluster_size:
        Number of failure-cluster members that motivated this lemma.
    impact_score:
        Estimated proof-space coverage if this lemma were verified [0, 1].
    verification_result:
        Current verifier status.
    source_node_ids:
        IDs of the cluster source nodes.
    created_at:
        Unix timestamp.
    """

    lemma_id: str
    statement: str
    proof_sketch: str
    cluster_size: int
    impact_score: float
    verification_result: VerificationResult
    source_node_ids: List[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return {
            "lemma_id": self.lemma_id,
            "statement": self.statement,
            "proof_sketch": self.proof_sketch,
            "cluster_size": self.cluster_size,
            "impact_score": self.impact_score,
            "verification_result": self.verification_result.value,
            "source_node_ids": self.source_node_ids,
            "created_at": self.created_at,
        }


# ---------------------------------------------------------------------------
# Lemma Discovery Engine
# ---------------------------------------------------------------------------


class LemmaDiscoveryEngine:
    """Discover bridging lemmas from proof-graph failure regions.

    Parameters
    ----------
    store:
        ``ProofGraphStore`` to analyse.
    curvature_analyzer:
        Pre-built ``CurvatureAnalyzer`` for hotspot detection.
    verifier:
        Active proof verifier.
    min_cluster_size:
        Minimum failure cluster size to generate a lemma.
    top_k:
        Maximum lemma candidates to return per discovery cycle.
    """

    def __init__(
        self,
        store: Optional[ProofGraphStore] = None,
        curvature_analyzer: Optional[CurvatureAnalyzer] = None,
        verifier: Optional[Verifier] = None,
        min_cluster_size: Optional[int] = None,
        top_k: Optional[int] = None,
    ) -> None:
        self._store = store or get_store()
        self._curvature = curvature_analyzer or get_curvature_analyzer()
        self._verifier = verifier or Verifier()
        self._min_cluster = min_cluster_size or cfg.LEMMA_MIN_CLUSTER_SIZE
        self._top_k = top_k or cfg.LEMMA_TOP_K
        self._encoder = get_encoder()
        self._lock = threading.Lock()
        # Cache of discovered candidates: lemma_id → LemmaCandidate
        self._candidates: Dict[str, LemmaCandidate] = {}

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def discover(self) -> List[LemmaCandidate]:
        """Run one discovery cycle and return ranked lemma candidates.

        Steps
        -----
        1. Find high-curvature hotspot nodes.
        2. Collect failure edges around each hotspot.
        3. Cluster failure-source nodes by embedding proximity.
        4. Generate a candidate lemma per cluster.
        5. Verify each candidate; keep only VERIFIED or PENDING ones.
        6. Rank by impact score and return top-k.
        """
        hotspots = self._curvature.top_curvature_nodes(top_k=20, radius=2)
        if not hotspots:
            logger.debug("Lemma discovery: no hotspots found")
            return []

        # Collect failed-edge source nodes near hotspots
        failure_nodes: List[ProofStateNode] = []
        seen_ids: Set[str] = set()
        for node_id, _score in hotspots:
            neighbourhood = self._store.bfs(node_id, max_depth=1)
            for node in neighbourhood:
                if node.node_id in seen_ids:
                    continue
                for _target, edge in self._store.successors(node.node_id):
                    if edge.verification_result == VerificationResult.FAILED:
                        failure_nodes.append(node)
                        seen_ids.add(node.node_id)
                        break

        if not failure_nodes:
            logger.debug("Lemma discovery: no failure nodes found")
            return []

        clusters = self._cluster(failure_nodes)
        logger.info(
            "Lemma discovery: %d failure nodes → %d clusters",
            len(failure_nodes),
            len(clusters),
        )

        candidates: List[LemmaCandidate] = []
        for cluster in clusters:
            if len(cluster) < self._min_cluster:
                continue
            candidate = self._generate_candidate(cluster)
            # Verify
            vr = self._verifier.verify(candidate.statement, candidate.proof_sketch)
            candidate.verification_result = vr
            if vr != VerificationResult.FAILED:
                with self._lock:
                    self._candidates[candidate.lemma_id] = candidate
                candidates.append(candidate)

        # Rank by impact score, deduplicate, return top-k
        candidates.sort(key=lambda c: c.impact_score, reverse=True)
        return candidates[: self._top_k]

    def get_all_candidates(self) -> List[LemmaCandidate]:
        """Return all previously discovered (non-failed) candidates."""
        with self._lock:
            return sorted(
                self._candidates.values(),
                key=lambda c: c.impact_score,
                reverse=True,
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _cluster(
        self, nodes: List[ProofStateNode], threshold: float = 0.70
    ) -> List[List[ProofStateNode]]:
        """Greedy single-linkage clustering in embedding space.

        Two nodes are in the same cluster if their cosine similarity
        exceeds ``threshold``.
        """
        if not nodes:
            return []

        # Encode nodes that don't yet have an embedding
        for node in nodes:
            if node.embedding is None:
                node.embedding = self._encoder.encode(node.proof_state)

        clusters: List[List[ProofStateNode]] = []
        assigned: Set[str] = set()

        for node in nodes:
            if node.node_id in assigned:
                continue
            cluster = [node]
            assigned.add(node.node_id)
            for other in nodes:
                if other.node_id in assigned:
                    continue
                if (
                    node.embedding is not None
                    and other.embedding is not None
                    and node.embedding.cosine_similarity(other.embedding) >= threshold
                ):
                    cluster.append(other)
                    assigned.add(other.node_id)
            clusters.append(cluster)

        return clusters

    def _generate_candidate(
        self, cluster: List[ProofStateNode]
    ) -> LemmaCandidate:
        """Generate a bridging lemma candidate from a failure cluster.

        The candidate statement is assembled from the most common goal
        fragment across cluster members and a schematic proof sketch.
        In a full implementation this would call an LLM to generate a
        more precise formal statement.
        """
        goals = [n.proof_state.goal for n in cluster]
        # Use the most common goal as the statement basis
        statement_base = max(set(goals), key=goals.count)
        statement = f"lemma bridging_lemma : {statement_base} := by"
        proof_sketch = "  sorry"  # placeholder; real prover would fill this in

        # Stable ID derived from statement text
        lemma_id = hashlib.sha256(statement.encode()).hexdigest()[:16]

        # Impact score heuristic: larger cluster with deeper nodes → higher impact
        mean_depth = sum(n.depth for n in cluster) / len(cluster)
        impact = min(1.0, len(cluster) / 10.0) * (1.0 + math.log1p(mean_depth) / 5.0)
        impact = min(1.0, impact)

        return LemmaCandidate(
            lemma_id=lemma_id,
            statement=statement,
            proof_sketch=proof_sketch,
            cluster_size=len(cluster),
            impact_score=impact,
            verification_result=VerificationResult.PENDING,
            source_node_ids=[n.node_id for n in cluster],
        )

# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_engine_instance: Optional[LemmaDiscoveryEngine] = None
_engine_lock = threading.Lock()


def get_lemma_engine() -> LemmaDiscoveryEngine:
    """Return the process-global ``LemmaDiscoveryEngine`` singleton."""
    global _engine_instance
    if _engine_instance is None:
        with _engine_lock:
            if _engine_instance is None:
                _engine_instance = LemmaDiscoveryEngine()
    return _engine_instance
