from __future__ import annotations

"""OpenClaw-inspired trading primitives for prediction market strategies."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, Iterable, List

# Probability guardrails — keeps Kelly sizing numerically stable.
MIN_PROBABILITY: float = 0.01
MAX_PROBABILITY: float = 0.99


@dataclass
class TradeSignal:
    """Represents an actionable signal generated by the trading agent."""

    market_id: str
    side: str
    confidence: float
    edge: float
    fair_value: float
    market_price: float
    rationale: str
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class PositionManager:
    """Tracks open positions and position sizing constraints."""

    max_position_fraction: float = 0.1
    open_positions: Dict[str, Dict[str, float]] = field(default_factory=dict)


class OpenClawTradingAgent:
    """Generates signals and position recommendations with adaptive win-rate tracking."""

    def __init__(self) -> None:
        self.position_manager = PositionManager()
        self.win_rate_ema = 0.55
        self.learning_rate = 0.2

    def generate_signal(self, market: Dict[str, float], model_probability: float) -> TradeSignal:
        """Convert a probability forecast into a directional trade signal."""
        analysis = self.evaluate_polymarket_market(market, model_probability)
        side = 'buy_yes' if analysis['edge'] >= 0 else 'buy_no'
        return TradeSignal(
            market_id=str(market['id']),
            side=side,
            confidence=round(abs(analysis['edge']) * 3 + self.win_rate_ema, 4),
            edge=round(analysis['edge'], 4),
            fair_value=round(model_probability, 4),
            market_price=round(float(market['probability']), 4),
            rationale=analysis['rationale'],
        )

    def evaluate_polymarket_market(self, market: Dict[str, float], model_probability: float) -> Dict[str, float]:
        """Estimate the edge between model probability and market probability."""
        market_probability = float(market['probability'])
        edge = model_probability - market_probability
        return {
            'edge': edge,
            'market_probability': market_probability,
            'fair_value': model_probability,
            'rationale': f"Model probability {model_probability:.2%} vs market {market_probability:.2%}.",
        }

    def manage_position(self, signal: TradeSignal, bankroll: float) -> Dict[str, float]:
        """Use Kelly sizing with guardrails to manage position exposure."""
        edge_probability = min(max(signal.fair_value, MIN_PROBABILITY), MAX_PROBABILITY)
        odds = max((1.0 / max(signal.market_price, MIN_PROBABILITY)) - 1.0, MIN_PROBABILITY)
        kelly = self.calculate_kelly_fraction(edge_probability, odds)
        fraction = min(kelly, self.position_manager.max_position_fraction)
        size = round(bankroll * fraction, 2)
        self.position_manager.open_positions[signal.market_id] = {
            'fraction': fraction,
            'size': size,
            'edge': signal.edge,
        }
        return {
            'market_id': signal.market_id,
            'kelly_fraction': round(kelly, 4),
            'applied_fraction': round(fraction, 4),
            'recommended_size': size,
        }

    def calculate_kelly_fraction(self, win_probability: float, odds: float) -> float:
        """Calculate a half-Kelly sizing recommendation."""
        raw = ((win_probability * (odds + 1)) - 1) / odds
        return max(raw * 0.5, 0.0)

    def update_win_rate_model(self, trade_outcomes: Iterable[bool]) -> float:
        """Update the internal win-rate estimate using an exponential moving average."""
        for outcome in trade_outcomes:
            observation = 1.0 if outcome else 0.0
            self.win_rate_ema = (self.learning_rate * observation) + ((1 - self.learning_rate) * self.win_rate_ema)
        return round(self.win_rate_ema, 4)
