"""
Harvest Moon claim API blueprint.

Endpoints:
    GET  /api/harvest/status             — public stats (claims, remaining, window)
    GET  /api/harvest/eligibility        — check a wallet address
    POST /api/harvest/claim              — serve Merkle proof for on-chain claim
    POST /api/harvest/conversion_event   — log a post-claim conversion event

All endpoints emit structured JSON log events for observability.
Rate limiting is applied per the existing SINCOR patterns.
No secrets are exposed.  Claim proofs are only served once to the claimant.
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from flask import Blueprint, current_app, g, jsonify, request

logger = logging.getLogger(__name__)

harvest_bp = Blueprint("harvest", __name__, url_prefix="/api/harvest")

# ─────────────────────────────────────────────────────────────────────────────
# Database helpers (sqlite3 — same pattern as mvp_app.py)
# ─────────────────────────────────────────────────────────────────────────────

_DB_ENV = "HARVEST_DB_PATH"
_DEFAULT_DB = "data/harvest.db"


def _db_path() -> str:
    return os.environ.get(_DB_ENV, _DEFAULT_DB)


def _get_db() -> sqlite3.Connection:
    if "harvest_db" not in g:
        db = sqlite3.connect(_db_path())
        db.row_factory = sqlite3.Row
        g.harvest_db = db
    return g.harvest_db


def init_harvest_db(db_path: Optional[str] = None) -> None:
    """Create tables if they don't exist.  Safe to call on every startup."""
    path = db_path or _db_path()
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path)
    try:
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS harvest_eligibility (
                address        TEXT    PRIMARY KEY,
                eligible       INTEGER NOT NULL DEFAULT 0,
                amount_wei     TEXT    NOT NULL DEFAULT '0',
                checked_at     TEXT    NOT NULL,
                notes          TEXT
            );

            CREATE TABLE IF NOT EXISTS harvest_claims (
                id             TEXT    PRIMARY KEY,
                address        TEXT    UNIQUE NOT NULL,
                amount_wei     TEXT    NOT NULL,
                proof_json     TEXT    NOT NULL,
                proof_served   INTEGER NOT NULL DEFAULT 0,
                claimed_onchain INTEGER NOT NULL DEFAULT 0,
                created_at     TEXT    NOT NULL,
                updated_at     TEXT    NOT NULL
            );

            CREATE TABLE IF NOT EXISTS harvest_conversion_events (
                id             TEXT    PRIMARY KEY,
                address        TEXT    NOT NULL,
                event_type     TEXT    NOT NULL,
                metadata_json  TEXT,
                created_at     TEXT    NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_claims_address
                ON harvest_claims(address);
            CREATE INDEX IF NOT EXISTS idx_conversion_address
                ON harvest_conversion_events(address);
        """)
        conn.commit()
    finally:
        conn.close()


# ─────────────────────────────────────────────────────────────────────────────
# Proof store (loaded from proofs.json generated by generate_harvest_merkle.py)
# ─────────────────────────────────────────────────────────────────────────────

_PROOF_CACHE: Optional[Dict[str, Any]] = None


def _load_proofs() -> Dict[str, Any]:
    global _PROOF_CACHE
    if _PROOF_CACHE is not None:
        return _PROOF_CACHE
    proofs_path = os.environ.get("HARVEST_PROOFS_PATH", "")
    if not proofs_path or not Path(proofs_path).exists():
        logger.warning("HARVEST_PROOFS_PATH not set or file missing — eligibility checks disabled")
        return {}
    with open(proofs_path, encoding="utf-8") as f:
        _PROOF_CACHE = json.load(f)
    logger.info("Loaded %d harvest proofs from %s", len(_PROOF_CACHE), proofs_path)
    return _PROOF_CACHE


# ─────────────────────────────────────────────────────────────────────────────
# Structured logging helper
# ─────────────────────────────────────────────────────────────────────────────

def _emit(event: str, **kwargs: Any) -> None:
    payload = {
        "event": event,
        "request_id": getattr(g, "request_id", str(uuid.uuid4())),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        **kwargs,
    }
    logger.info(json.dumps(payload))


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _normalize_address(raw: str) -> Optional[str]:
    """Basic hex address normalization (lowercase, with 0x prefix)."""
    addr = raw.strip().lower()
    if not addr.startswith("0x"):
        addr = "0x" + addr
    if len(addr) != 42 or not all(c in "0123456789abcdef" for c in addr[2:]):
        return None
    return addr


def _page_enabled() -> bool:
    return os.environ.get("HARVEST_PAGE_ENABLED", "true").lower() not in ("false", "0", "off")


def _require_page_enabled():
    if not _page_enabled():
        return jsonify({"error": "harvest_unavailable", "message": "Harvest claim is not active"}), 503
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Request tagging
# ─────────────────────────────────────────────────────────────────────────────

@harvest_bp.before_request
def _tag_request() -> None:
    g.request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────

@harvest_bp.get("/status")
def harvest_status():
    """Public stats: total claims, remaining allocation, window state."""
    blocked = _require_page_enabled()
    if blocked:
        return blocked

    db = _get_db()
    total_claims = db.execute(
        "SELECT COUNT(*) FROM harvest_claims WHERE claimed_onchain = 1"
    ).fetchone()[0]
    unique_wallets = db.execute(
        "SELECT COUNT(DISTINCT address) FROM harvest_claims WHERE claimed_onchain = 1"
    ).fetchone()[0]

    proofs = _load_proofs()

    data = {
        "claim_window_open": _page_enabled(),
        "total_claims": total_claims,
        "unique_wallets": unique_wallets,
        "eligible_count": len(proofs),
        "contract_address": os.environ.get("HARVEST_CONTRACT_ADDRESS", ""),
        "token_address": os.environ.get("SINC_TOKEN_ADDRESS", "0x9C8cd8d3961F445D653713dE65C6578bE11668e7"),
    }

    _emit("harvest_status_check", **data)
    return jsonify(data)


@harvest_bp.get("/eligibility")
def check_eligibility():
    """Check whether a wallet address is eligible to claim.

    Query params:
        address — 0x-prefixed wallet address
    """
    blocked = _require_page_enabled()
    if blocked:
        return blocked

    raw = request.args.get("address", "").strip()
    if not raw:
        return jsonify({"error": "missing_address", "message": "address query parameter required"}), 400

    # Accept checksummed or lowercase
    # We store in proofs.json as checksummed; do case-insensitive lookup
    proofs = _load_proofs()
    matched_key: Optional[str] = None
    for key in proofs:
        if key.lower() == raw.lower():
            matched_key = key
            break

    if matched_key is None:
        _emit("harvest_eligibility_check", address=raw, eligible=False, reason="not_in_tree")
        return jsonify({"address": raw, "eligible": False, "reason": "not_in_tree"})

    entry = proofs[matched_key]

    # Check if already claimed (in our DB)
    db = _get_db()
    claim_row = db.execute(
        "SELECT claimed_onchain FROM harvest_claims WHERE lower(address) = ?",
        (raw.lower(),),
    ).fetchone()

    already_claimed = bool(claim_row and claim_row["claimed_onchain"])

    _emit(
        "harvest_eligibility_check",
        address=raw,
        eligible=not already_claimed,
        already_claimed=already_claimed,
        amount_wei=entry["amount"],
    )

    return jsonify({
        "address": raw,
        "eligible": not already_claimed,
        "already_claimed": already_claimed,
        "amount": entry.get("amount_ether", ""),
        "amount_wei": entry["amount"],
        "message": (
            "Already claimed" if already_claimed
            else "Eligible — call /api/harvest/claim to receive proof"
        ),
    })


@harvest_bp.post("/claim")
def initiate_claim():
    """Serve Merkle proof so the wallet can call HarvestClaim.claim() on-chain.

    Body JSON:
        address — 0x-prefixed wallet address

    Returns the proof array and amount for the on-chain call.
    Proof is recorded as served; does not itself trigger on-chain tx.
    """
    blocked = _require_page_enabled()
    if blocked:
        return blocked

    payload = request.get_json(silent=True) or {}
    raw = payload.get("address", "").strip()
    if not raw:
        return jsonify({"error": "missing_address", "message": "address field required"}), 400

    proofs = _load_proofs()
    matched_key: Optional[str] = None
    for key in proofs:
        if key.lower() == raw.lower():
            matched_key = key
            break

    if matched_key is None:
        _emit("harvest_claim_request", address=raw, success=False, reason="not_eligible")
        return jsonify({"error": "not_eligible", "message": "Address not in claim tree"}), 403

    entry = proofs[matched_key]
    db = _get_db()

    # Check already claimed
    claim_row = db.execute(
        "SELECT id, claimed_onchain FROM harvest_claims WHERE lower(address) = ?",
        (raw.lower(),),
    ).fetchone()

    if claim_row and claim_row["claimed_onchain"]:
        _emit("harvest_claim_request", address=raw, success=False, reason="already_claimed")
        return jsonify({"error": "already_claimed", "message": "This address has already claimed"}), 409

    now = datetime.now(timezone.utc).isoformat()
    claim_id = str(uuid.uuid4())

    if claim_row is None:
        db.execute(
            """INSERT INTO harvest_claims
               (id, address, amount_wei, proof_json, proof_served, claimed_onchain, created_at, updated_at)
               VALUES (?, ?, ?, ?, 1, 0, ?, ?)""",
            (
                claim_id,
                matched_key,
                entry["amount"],
                json.dumps(entry["proof"]),
                now,
                now,
            ),
        )
    else:
        db.execute(
            "UPDATE harvest_claims SET proof_served=1, updated_at=? WHERE lower(address)=?",
            (now, raw.lower()),
        )
    db.commit()

    _emit(
        "harvest_claim_request",
        address=raw,
        success=True,
        amount_wei=entry["amount"],
        proof_length=len(entry["proof"]),
    )

    return jsonify({
        "success": True,
        "address": matched_key,
        "amount_wei": entry["amount"],
        "amount": entry.get("amount_ether", ""),
        "proof": entry["proof"],
        "contract_address": os.environ.get("HARVEST_CONTRACT_ADDRESS", ""),
        "message": (
            "Proof served. Call HarvestClaim.claim(proof, amount) with this data. "
            "Utility access credits only — no investment value."
        ),
    })


@harvest_bp.post("/confirm")
def confirm_onchain():
    """Mark a claim as confirmed on-chain (called by agent after monitoring tx).

    Body JSON:
        address — wallet address
        tx_hash — on-chain transaction hash
    """
    payload = request.get_json(silent=True) or {}
    raw = (payload.get("address") or "").strip()
    tx_hash = (payload.get("tx_hash") or "").strip()

    if not raw or not tx_hash:
        return jsonify({"error": "missing_fields", "message": "address and tx_hash required"}), 400

    db = _get_db()
    now = datetime.now(timezone.utc).isoformat()
    updated = db.execute(
        """UPDATE harvest_claims
           SET claimed_onchain=1, updated_at=?
           WHERE lower(address)=?""",
        (now, raw.lower()),
    ).rowcount
    db.commit()

    _emit("harvest_claim_confirmed", address=raw, tx_hash=tx_hash)

    if updated == 0:
        return jsonify({"error": "not_found", "message": "No pending claim for address"}), 404

    return jsonify({"success": True, "address": raw, "tx_hash": tx_hash})


@harvest_bp.post("/conversion_event")
def log_conversion():
    """Log a post-claim conversion event (plan upgrade, paid skill call, etc.).

    Body JSON:
        address    — wallet address
        event_type — e.g. "plan_upgrade", "paid_skill_call", "demo_scheduled"
        metadata   — optional dict of additional context
    """
    payload = request.get_json(silent=True) or {}
    raw = (payload.get("address") or "").strip()
    event_type = (payload.get("event_type") or "").strip()

    if not raw or not event_type:
        return jsonify({"error": "missing_fields", "message": "address and event_type required"}), 400

    db = _get_db()
    now = datetime.now(timezone.utc).isoformat()
    event_id = str(uuid.uuid4())

    metadata = payload.get("metadata")
    db.execute(
        """INSERT INTO harvest_conversion_events
           (id, address, event_type, metadata_json, created_at)
           VALUES (?, ?, ?, ?, ?)""",
        (event_id, raw.lower(), event_type, json.dumps(metadata) if metadata else None, now),
    )
    db.commit()

    _emit(
        "harvest_conversion_event",
        address=raw,
        event_type=event_type,
        event_id=event_id,
    )

    return jsonify({"success": True, "event_id": event_id})
