# universal_manifester.py
# Reads job + paths/<path>.json, makes a write_manifest with placeholders for all listed deliverables.

import json, base64, time
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]  # ...\sincor_33
RUNTIME = ROOT / "runtime"
INBOX = RUNTIME / "inbox"
WF = RUNTIME / "write_manifest.json"
PATHS = ROOT / "paths"
OUTDIR = ROOT / "output"

def b64(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")

def placeholder_for(path: Path, meta: dict) -> dict:
    # Return a manifest "write" entry appropriate for the extension
    ext = path.suffix.lower()
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    info = {
        "note": "placeholder generated by universal_manifester",
        "biz": meta.get("biz"),
        "city": meta.get("city"),
        "path_id": meta.get("path"),
        "ts": ts
    }
    if ext in (".json",):
        return {"path": str(path), "text": json.dumps(info, indent=2)}
    if ext in (".html", ".csv", ".txt", ".svg"):
        return {"path": str(path), "text": f"PLACEHOLDER {ext} for {info['biz']} @ {ts}\n"}
    if ext in (".pdf", ".zip"):
        payload = f"{ext.upper()} PLACEHOLDER for {info['biz']} @ {ts}\n".encode("utf-8")
        return {"path": str(path), "payload_b64": b64(payload)}
    # Default to text
    return {"path": str(path), "text": f"PLACEHOLDER for {info['biz']} @ {ts}\n"}

def load_job(timeout_s: int = 30) -> Path | None:
    # wait briefly for job_*.json to appear
    end = time.time() + timeout_s
    last = None
    while time.time() < end:
        jobs = sorted(INBOX.glob("job_*.json"))
        if jobs:
            last = jobs[-1]
            break
        time.sleep(0.2)
    return last

def main():
    RUNTIME.mkdir(parents=True, exist_ok=True)
    INBOX.mkdir(parents=True, exist_ok=True)
    OUTDIR.mkdir(parents=True, exist_ok=True)

    job_file = load_job()
    if not job_file:
        print("[universal_manifester] no job found")
        return
    job = json.loads(job_file.read_text(encoding="utf-8-sig"))
    path_id = job.get("path")
    if not path_id:
        print("[universal_manifester] job missing 'path'")
        return

    pfile = PATHS / f"{path_id}.json"
    if not pfile.exists():
        print(f"[universal_manifester] path manifest not found: {pfile}")
        return
    p = json.loads(pfile.read_text(encoding="utf-8"))

    # Build planned writes for each deliverable in the path manifest
    writes = []
    for rel in p.get("deliverables", []):
        target = ROOT / rel
        writes.append(placeholder_for(target, job|{"path": path_id}))

    # Merge with existing manifest if present (append)
    if WF.exists():
        try:
            data = json.loads(WF.read_text(encoding="utf-8"))
            existing = data.get("writes", [])
        except Exception:
            existing = []
    else:
        existing = []

    data = {"writes": existing + writes}
    WF.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"[universal_manifester] wrote {len(writes)} entries to {WF}")

if __name__ == "__main__":
    main()
